# Generated by Django 3.2.7 on 2021-09-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=10000)),
                ('orignal_name', models.CharField(blank=True, default='', max_length=10000)),
                ('password', models.CharField(blank=True, default='', max_length=10000)),
                ('country', models.CharField(blank=True, default='', max_length=10000)),
                ('longitude', models.CharField(blank=True, default='', max_length=10000)),
                ('latitude', models.CharField(blank=True, default='', max_length=10000)),
                ('state', models.CharField(blank=True, default='', max_length=10000)),
                ('reset_code', models.CharField(blank=True, default='', max_length=10000)),
                ('generated_name', models.CharField(blank=True, default='', max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=10000)),
                ('description', models.CharField(blank=True, default='', max_length=1000000)),
                ('place_name', models.CharField(blank=True, default='', max_length=1000000)),
                ('longitude', models.CharField(blank=True, default='', max_length=10000)),
                ('latitude', models.CharField(blank=True, default='', max_length=10000)),
                ('event_date', models.CharField(blank=True, default='', max_length=10000)),
                ('date_object', models.DateField(blank=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='root.initiative_category')),
                ('enrolled', models.ManyToManyField(related_name='enrolled', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
