# Generated by Django 3.2.7 on 2021-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative_table',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000000),
        ),
    ]
