# Generated by Django 3.2.7 on 2021-09-18 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0003_alter_initiative_table_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative_table',
            name='is_green_area',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='initiative_table',
            name='date_object',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative_table',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='initiative_table',
            name='event_date',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
