# Generated by Django 3.2.7 on 2021-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative_table',
            name='participant_badge',
            field=models.ManyToManyField(blank=True, related_name='participant_badge', to='root.Badges'),
        ),
    ]
