# Generated by Django 3.2.7 on 2021-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20210926_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='participant_badges',
        ),
    ]
