# Generated by Django 3.2.7 on 2021-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_remove_profile_participant_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='participant_badges',
            field=models.CharField(blank=True, default='[]', max_length=10000),
        ),
    ]
