# Generated by Django 3.2.7 on 2021-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20210926_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative_table',
            name='particiapnt_badges',
            field=models.ManyToManyField(default=None, to='root.Badges_Container'),
        ),
    ]
