# Generated by Django 3.2.7 on 2021-09-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_initiative_table_particiapnt_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges_container',
            name='user',
        ),
        migrations.AddField(
            model_name='badges_container',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.profile'),
        ),
    ]
