# Generated by Django 3.2.7 on 2021-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20211015_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=10000)),
                ('text', models.CharField(blank=True, default='', max_length=10000)),
                ('date', models.DateField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(blank=True, default=0, null=True)),
                ('reply_count', models.IntegerField(blank=True, default=0, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('quote_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
