# Generated by Django 3.2.7 on 2021-10-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_auto_20211019_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet_table',
            old_name='date',
            new_name='created_at',
        ),
    ]
