# Generated by Django 3.2.8 on 2021-10-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_tweet_table_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imported_Tweet_Table',
        ),
    ]
