# Generated by Django 3.2.8 on 2021-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_imported_tweet_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_table',
            name='profile_image_url',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
